flags: {}
extra-lib-dirs:
  - /usr/local/lib

packages:
- ../crucible-public/crucible
- ../crucible-public/crucible-abc
- ../crucible-public/crucible-blt
- ../crucible-public/crucible-saw
- ../crucible-public/crucible-server
- ../crucible-public/galois-matlab
- ../abcBridge
- ../aig
- ../hpb
- ../parameterized-utils
- ../saw-core
extra-deps:
- clock-0.5.2
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- llvm-pretty-0.4.0.1
- llvm-pretty-bc-parser-0.2.1.0
resolver: lts-5.3
