flags: {}
extra-lib-dirs:
  - /usr/local/lib

packages:
- ../mss/crucible
- ../mss/crucible-abc
- ../mss/crucible-saw
- ../mss/crucible-server
- ../mss/matlab-data
- ../abcBridge
- ../aig
- ../hpb
- ../parameterized-utils
- ../saw-core
- ../buffer-builder
extra-deps:
- clock-0.5.2
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- llvm-pretty-0.4.0.1
- llvm-pretty-bc-parser-0.2.1.0
resolver: lts-6.26
