flags: {}
extra-lib-dirs:
  - /usr/local/lib
compiler-check: newer-minor

packages:
- ../llvm-pretty
- ../crucible/crucible
- ../crucible/crucible-abc
- ../crucible/crucible-saw
- ../crucible/crucible-server
- ../crucible/galois-matlab
- ../abcBridge
- ../aig
- ../hpb
- ../parameterized-utils
- ../saw-core
- ../buffer-builder
extra-deps:
- clock-0.5.2
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- llvm-pretty-bc-parser-0.3.0.0
resolver: lts-6.26
