flags: {}
packages:
- ../mss/crucible
- ../mss/crucible-abc
- ../mss/crucible-server
- ../mss/galois-matlab
- ../abcBridge
- ../aig
- ../hpb
- ../parameterized-utils
extra-deps:
- llvm-pretty-0.3.1.1
- llvm-pretty-bc-parser-0.1.3.1
resolver: nightly-2015-06-30
