flags: {}
packages:
- ../mss/crucible
- ../mss/crucible-abc
- ../mss/crucible-saw
- ../mss/crucible-server
- ../mss/galois-matlab
- ../abcBridge
- ../aig
- ../hpb
- ../parameterized-utils
- ../saw-core
extra-deps:
- bimap-0.3.1
- llvm-pretty-0.4.0.1
- llvm-pretty-bc-parser-0.2.1.0
resolver: lts-3.3
